fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\AppUser
  from_email:
    address: "test@test.com"
    sender_name: "test"
  registration:
    form:
      type: App\Form\RegistrationFormType

