security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_MEMBRE: ROLE_USER
        ROLE_MODERATEUR: ROLE_MEMBRE
        ROLE_ADMIN: [ROLE_MODERATEUR, ROLE_MUSEUM]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/mod-amin, role: ROLE_MODERATEUR }
        - { path: ^/mus-admin, role: ROLE_MUSEUM }
        - { path: ^/admin, role: ROLE_ADMIN }
